### ISSUE TITLE
dropins folder

### ISSUE THREAD

**Issue by maghibus** [ThejanRupasinghe/ei-elastic-custom-publisher#1] opened 2018-09-12 08:23 UTC
Hello,

> Copy the “org.wso2.custom.elastic.publisher_1.0.jar” in the “target” directory to the “dropins” directory of EI installation.

Doesn't seem to be working.

**Comment by ThejanRupasinghe** [comment] 2018-09-12 18:33
What is the EI version you are trying on? Can you provide EI error log/terminal output?

**Comment by maghibus** [comment] 2018-09-12 19:53
- wso2ei 6.1.1
- WSO2 Carbon Framework v4.4.16
- windows 10
- org.wso2.carbon.das.messageflow.data.publisher 4.6.19

If I copy the org.wso2.custom.elastic.publisher_1.0.jar in the dropins folder and i start _integrator.bat_ , the integrator will wait:
```
[2018-09-12 21:16:52,230] []  WARN - CarbonServerManager Carbon initialization is delayed due to the following unsatisfied items:
[2018-09-12 21:16:52,244] []  WARN - CarbonServerManager Waiting for required Module: org.wso2.custom.elastic.publisher-1.0
[2018-09-12 21:16:52,230] []  WARN - CarbonServerManager Carbon initialization is delayed due to the following unsatisfied items:
[2018-09-12 21:16:52,244] []  WARN - CarbonServerManager Waiting for required Module: org.wso2.custom.elastic.publisher-1.0 
```

So I copied the org.wso2.custom.elastic.publisher_1.0.jar in the lib folder and during startup i have seen 
**org.wso2.custom.elastic.publisher_1.0_1.0.0.jar** popping up in the dropins folder and previous WARN is gone. However, mediation flow observer is not running, because i cant't find any log line.

Thanks a lot

**Comment by ThejanRupasinghe** [comment] 2018-09-13 10:54
EI 6.1.1 had an [issue](https://github.com/wso2/product-ei/issues/843) in exposing the message flow publishing component. It was corrected in [this pr](https://github.com/wso2/carbon-mediation/pull/840). Can you check whether your EI 6.1.1 has this update?

**Comment by maghibus** [comment] 2018-09-14 07:43
I updated the last update and it works.
thank you

**Comment by ThejanRupasinghe** [comment] 2018-09-14 08:59
As the problem is resolved, I'm closing this issue. Feel free to reopen this, if it occurred again.

**Closed as completed by ThejanRupasinghe** 2018-09-14 08:59 UTC
